Discussion Image_of_issue.md
edu-xored/tracker pull request #2
Opened 2016-10-24 04:26 UTC by teabagk7

2016-10-25 09:20 UTC, dsavenko commented
Some things are not clear:

1. How the dates are stored (the date of opening and closing, as well as the dates of all changes to the issue);

2. How the user information is stored (who created/change/resolved the issue);

3. How to get a list of all issues based on status (all/opened/resolved);

2016-10-25 09:21 UTC, dsavenko requested changes
Some things are not clear:
1. How the dates are stored (the date of opening and closing, as well as the dates of all changes to the issue);
2. How the user information is stored (who created/change/resolved the issue);
3. How to get a list of all issues based on status (all/opened/resolved);

Please, clarify in the document.

2016-10-31 13:03 UTC, teabagk7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Изучить модель данных Git. Разработать план как реализовать хранение тикетов в Git'e в терминах этой модели.](https://trello.com/c/JBb8jvtM/1-git-git-e)

2016-10-31 13:09 UTC, dsavenko approved these changes

2016-11-02 07:47 UTC, akhismat commented on Image_of_issue.md
> +Создается новый blob с названием равным хэшу issue, содержащий в себе строку с хэшем issue. (В пункте *“изменение issue”* обосновываются причины создания этого blob объекта). Из этого blob объекта со
Имя рефа "ISSUES", обнови пожалуйста

2016-11-02 07:51 UTC, AnnaKhismatullina commented
Предлагаю переименовать Image_of_issue.md в MODEL.md

2016-11-02 08:02 UTC, kevromster approved these changes

2016-11-02 16:06 UTC, makrushin-evgenii approved these changes

2016-11-03 05:53 UTC, akhismat reviewed
Я имела ввиду переимоновать файл в MODEL.md, а не заголовок пулл реквеста:)

2016-11-03 07:20 UTC, MaxIvanov1997 approved these changes

2016-11-03 10:08 UTC, Tatiotaeryy approved these changes

2016-11-03 11:32 UTC, akhismat approved these changes

2016-11-03 13:04 UTC, merged