Feature/9
edu-xored/tracker pull request #4
Opened 2016-11-06 15:34 UTC by teabagk7

May be problem with "^" in string №40.
Your criticism and suggestions, pls.

2016-11-07 04:50 UTC, teabagk7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Список открытых issues ('git bug')](https://trello.com/c/WTTUFY3k/9-issues-git-bug)

2016-11-07 11:58 UTC, AnnaKhismatullina commented on src/git-bug
> +				if [ "$1" = "--resolved" ]
Давайте использовать здесь switch вместо вложенных if-else

2016-11-07 11:59 UTC, AnnaKhismatullina commented on src/git-bug
> +					echo "$hash_of_commit" "$summary"
Эти 3 строчки используются 6 раз в этом файле. Пожалуйста, вынесите это в отдельную функцию.

2016-11-07 16:25 UTC, kevromster requested changes

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +else
зачем тут `else`, лучше в его if'е просто поставить `exit`, ну или то, что @AnnaKhismatullina предложила

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +	git bug-new $2 $3
ну вообще лучше все параметры передавать через `"$@"`. Если нужно при этом "выбросить" первый `$1`, то использовать команду `shift`, которая сдвинет аргументы (второй сделает первым, третий - вторым и т.д.)

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +		temp=`git show-ref --hash ISSUES`
имя `temp` не говорящее - нужно называть так, чтобы было понятно по коду, что это и для чего

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +		until [ "$PARENT" = "" ]
может традиционный `while`? )

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +			hash_of_commit=`git cat-file -p ${hash_of_blob:12:40}`
а что тут `:12:40` обозначает? вообще, в нетривиальных местах кода не запрещается делать комменты )

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +			temp=$temp^
а что здесь хотелось от `^`? если просто в `git log` следующий передать, ну так там и прописать

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +			summary=`git cat-file -p ${hash_of_summary:12:40}`
лучше в двойные кавычки заключить:
```summary="`git cat-file ...`"```
возможно, в других местах тоже, не присматривался

2016-11-07 16:25 UTC, kevromster commented on src/git-bug
> +		git bug-resolve $2
аналогично все переменные передавать

2016-11-08 14:48 UTC, teabagk7 commented on src/git-bug
> +			hash_of_commit=`git cat-file -p ${hash_of_blob:12:40}`
выделяем подстроку(hash) из строки

2016-11-09 04:10 UTC, AnnaKhismatullina commented on src/git-bug
> +if [ "$1" = "new" ]
Давай объявим переменную, назовем ее типа command или subcommand и присвоем ей значение параметра $1, будет четь понятнее, что происходит:)

2016-11-09 04:12 UTC, AnnaKhismatullina commented on src/git-bug
> +        shift
shift, пожалуй, можно делать всегда, не стоит плодить одинаковые строки в каждом if'e

2016-11-09 12:29 UTC, kevromster requested changes

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +print_issue()
Строку `#!...` лучше отделить пустой строкой от остального кода.

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +
Тут целых две пустые строки, а везде ниже - ни одной. Предлагаю более равномерно разделять код на логические части одной пустой строкой.

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +if  git show-ref --quiet --verify ISSUES;
Точка с запятой в конце, кажется, не нужна? Вообще, я бы весь код отсюда и до конца вынес в отдельную функцию с говорящим названием вроде _list_issues()_

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +cont_of_issues="`git ls-tree ISSUES`"
`count_of_issues`?

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +        string_length=94 #ТАК НЕОБХОДИМО потому что не работает  string_length="`expr index "$cont_of_issues" \n`" КАК НАЙТИ КОНЕЦ СТРОКИ?
а что за конец строки нужно найти? есть же команда _wc_, есть вся мощь _sed_ и _awk_

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +        hash_of_issue="${string:12:40}"
хотелось бы без хардкода магических цифр обойтись. На крайний случай - в отдельные говорящие константы вынести.

2016-11-09 12:29 UTC, kevromster commented on src/git-bug
> +		if [ "$#" -eq 0 ]
отступ от края непонятный. Видимо, табы вместо пробелов тут? Все отступы в коде нужно делать одинаковым образом - например пробелами.

2016-11-10 14:54 UTC, teabagk7 commented on src/git-bug
> +	git bug-new $2 $3
done

2016-11-10 14:55 UTC, teabagk7 commented on src/git-bug
> +				if [ "$1" = "--resolved" ]
done

2016-11-10 14:55 UTC, teabagk7 commented on src/git-bug
> +					echo "$hash_of_commit" "$summary"
done

2016-11-10 14:55 UTC, teabagk7 commented on src/git-bug
> +else
done

2016-11-10 15:26 UTC, kevromster requested changes

2016-11-10 15:26 UTC, kevromster commented on src/git-bug
> +	exit 0
кажется, лучше написать `exit $?` - выходить с кодом возврата `git bug-new`. Только надо проверить, что это правильно работает.

2016-11-10 15:26 UTC, kevromster commented on src/git-bug
> +	exit 0
а что данный выход означает? нет ишуёв?

2016-11-10 15:26 UTC, kevromster commented on src/git-bug
> +cont_of_issues="`git ls-tree ISSUES`"
`count_of_issues`? или тут какое-то секретное сокращение? ранее уже спрашивалось - don't ignore замечания, сделанные ранее

2016-11-11 04:10 UTC, teabagk7 commented on src/git-bug
> +cont_of_issues="`git ls-tree ISSUES`"
content

2016-11-11 09:23 UTC, kevromster requested changes

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +
лишняя пустая строка

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +	if ! git show-ref --quiet --verify $REF
давайте в одну строчку тоже превратим с помощью конструкции `[ ... ] && return`

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +
лишняя пустая строка

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +		local NAME_LENGTH=40
эта переменная нигде не используется

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +
лишняя пустая строка

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +
лишняя пустая строка

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +	echo "usage: git bug [-a | --open | --resolved] <subcommand>"
1) добавить опцию _-h_
2) без параметров `git bug` мы же тоже умеем и хотим запускать? как тогда скрипт отработает?
3) судя по скрипту, тут `<subcommand>` тоже опционален, т.е.: `git bug [-h | -a | --open | --resolved | <subcommand>]`

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +
лишняя пустая строка. Мы либо везде принимаем за правило отступать от начала скобки, либо нигде.

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +		"-h")
давайте ещё тут же `"--help"` добавим (по-моему, просто через `|` можно прямо тут прописать)

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +	if [ ! type "git_bug_$subcommand" ]
а это функция такая должна появиться после предыдущего `source`? если да, то мы, получается, завязываемся на детали реализации того скрипта. Почему бы здесь просто сразу не выполнить скрипт `"$workingdir/git-bug-$subcommand" "$@"` и вернуть его код возврата?

2016-11-11 09:23 UTC, kevromster commented on src/git-bug
> +		local issues_names="$(echo "$issues_names" | awk ' NR != 1 {print $0}')"
это будет работать, но на большом количестве ишуёв устроенный таким образом наш цикл `while` будет медленным. Ты, получается, на каждый проход по циклу перезаписываешь в новый массив всё, кроме первой строки. Стоит подумать об оптимизации - возможно, в отдельной задаче, чтобы сейчас не сильно тратить на это время.

2016-11-11 16:58 UTC, teabagk7 commented on src/git-bug
> +		"-h")
--help должен по умолчанию вызвать man,  насколько мне известно

2016-11-12 16:51 UTC, kevromster requested changes
Два замечания, и можно будет мерджить.

2016-11-12 16:51 UTC, kevromster commented on src/git-bug
> +		let "issue_number = issue_number + 1"
`let` - встроенная команда _bash_, но не _sh_. Первой строчкой в скрипте же указан _sh_, значит плюшки баша работать не будут. Давай тут просто напишем стандартный sh-инкремент:
```
issue_number=$((issue_number+1))
```
А больше нигде тут на баш завязки нет? я, вроде, заметил только это место.

2016-11-12 16:51 UTC, kevromster commented on src/git-bug
> +	source $workingdir/git-bug-$subcommand "$@"
Тут не нужен `source`, зачем? Он тебе фактически "вставит" содержимое другого скрипта в это место, а это не то, что мы хотим. Просто запускаем другой скрипт без всяких `source`, лучше с кавычками на случай пробелов в путях:
```
"$workingdir/git-bug-$subcommand" "$@"
```
В остальном скрипт выглядит ок.

2016-11-13 15:18 UTC, teabagk7 commented on src/git-bug
> +		let "issue_number = issue_number + 1"
Похоже, что только здесь.
Поправлю

2016-11-14 03:33 UTC, kevromster approved these changes
LGTM

2016-11-14 12:19 UTC, akhismat approved these changes

2016-11-14 12:19 UTC, merged