git bug new
edu-xored/tracker pull request #5
Opened 2016-11-06 16:13 UTC by Tatiotaeryy

2016-11-07 04:51 UTC, teabagk7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать команду создания нового тикета ('git bug new')](https://trello.com/c/a0646ZAg/2-git-bug-new)

2016-11-07 12:45 UTC, AnnaKhismatullina commented on src/commands/git-bug-new
> +FILE=".viin"
Зачем нужен этот файл и почему у него такое имя?

2016-11-07 12:46 UTC, akhismat commented on src/commands/git-bug-new
> +	git rm status >> /dev/null
Что такое dev/null? Зачем мы туда что-то пишем?

2016-11-07 16:05 UTC, kevromster requested changes

2016-11-07 16:05 UTC, kevromster commented on src/commands/git-bug-new
> +	git rm status >> /dev/null
Обычно туда сбрасывают мусорный вывод, который стразу уничтожается и не выводится на экран либо куда-либо ещё.
Видимо, здесь мы не хотим, чтобы пользователь, запустивший этот скрипт, видел логи этих промежуточных команд.
Только обычно с `/dev/null` работают не через `>>`, а через `>`, ну и поток ошибок `stderr` тоже можно спрятать (если надо) вот так:
`echo 'blablabla' > /dev/null 2>&1`

2016-11-07 16:05 UTC, kevromster commented on src/commands/git-bug-new
> +	echo $2 > $FILE
а если второго параметра нет? нужна проверка корректности входных параметров

2016-11-07 16:05 UTC, kevromster commented on src/commands/git-bug-new
> +		mv ./.git/index ./.git/index2
во-первых, почему без `-f` параметра (чтобы не спрашивать у пользователя подтверждения), во-вторых, имя `index2` не очень (а вдруг оно занято будет в новых версиях гита?) - обычно для временных промежуточных файлов лучше использовать в качестве суффикса специальную переменную `$$`, означающую PID текущего процесса.

2016-11-07 16:05 UTC, kevromster commented on src/commands/git-bug-new
> +	rm ./.git/index
везде `rm -f` лучше использовать, опять же чтобы не спрашивать пользователя подтверждения операции

2016-11-07 16:05 UTC, kevromster commented on src/commands/git-bug-new
> +if [ -f $FILE ]
Эти четыре строчки if'а можно переписать в одну так: `[ <условие> ] && <действие>` - не только здесь, но и в других аналогичных местах этого скрипта.
А конкретно тут так, с кавычками вокруг `$FILE`, так как в его имени или пути могут быть пробелы:
`[ -f "$FILE" ] && rm -f "$FILE"`

2016-11-10 15:11 UTC, kevromster requested changes

2016-11-10 15:11 UTC, kevromster commented on Makefile
> +	find "$(SRC_PATH)" -name '$(SRC_OBJ)-*' -exec rm {} \;
Непонятно, почему фиксы Makefile делаются в этой ветке - они же не относятся к задаче?
Если нашлась какая-то ошибка в коде, не связанном с производимым изменением, заводится отдельная бага в трэкере задач и фиксится в своей ветке.
В данном случае пусть @AnnaKhismatullina решит, выносить это в отдельную ветку или оставить уже тут на первый раз :)

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +FILE=".viin"
уже спрашивалось, почему такое страное имя? лучше какой-нибудь `/tmp/blabla$$` создать, а то здесь рискуем пересечься с файлами пользователя репозитория.

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +if [ -s "$FILE" ]
предлагаю инвертировать условие - если файла нет, то сразу exit, можно с выводом в консоль, что не предоставлено описание ишуя

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +	LINE=`head -1 $FILE`
А вдруг юзер пустой файл оставил или там одними пробелами заполнил? Кажется, перед любыми манипуляциями с `git`, стоит проверить, что контент не пуст. Ну и LINE стоит strip'нуть от окружающих пробелов. Плюс поставить тут и в других местах двойные кавычки.

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $STATUS status
кажется, здесь и ниже нужно в кавычках писать "$STATUS", "$DESCRIPTION", etc? чтобы длинные строки с пробелами правильно обрабатывались

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +	[ -f "./.git/index" ] && mv -f "./.git/index" "./.git/index$$"
в другом PR уже писал - зависим от относительного местоположения и думаем, что запускаем скрипт из корня проекта. А если я в подпапку перейду?

2016-11-10 15:11 UTC, kevromster commented on src/commands/git-bug-new
> +	rm -f "./.git/index"
тот же вопрос, что и в другом PR - зачем этот файл тут удалять? следующий же `mv` его просто перетрёт

2016-11-11 17:55 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	rm -f "./.git/index"
Если перемещаемого файла нет, то затирать его будет нечем, а следы подчищать надо.

2016-11-11 17:58 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $STATUS status
Здесь в STATUS, DESCRIPTION, SUMMARY хранятся хэши соответствующих блобов, насколько мне известно в шестнадцатеричную запись пробелы не входят.

2016-11-11 17:58 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	LINE=`head -1 $FILE`
Спасибо, исправили.

2016-11-14 15:07 UTC, kevromster requested changes

2016-11-14 15:07 UTC, kevromster commented on src/commands/git-bug-new
> +	until [ -d ./.git ]; do cd ..; done; echo "$PWD/.git";
А если _.git_ так и не найдётся?

2016-11-14 15:07 UTC, kevromster commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
1) Может, добавить `$$` к имени временного файла? Если в текущем виде ты два раза одновременно запустишь скрипт в одном репе, что произойдёт?
2) Непонятно, зачем его в $GIT_DIR прятать. Если вдруг скрипт развалится посередине, пользователь его и не увидит.

2016-11-14 15:07 UTC, kevromster commented on src/commands/git-bug-new
> +	[ ! -s "$FILE" ] && rm -f "$FILE" && exit 0
ну, строго говоря, тут всегда нужно делать `exit`, даже если `rm` почему-то вернёт ошибку.
Касательно всего кода: обычно, если выходим с ошибкой, то это не 0, а, например, 1.

2016-11-14 15:07 UTC, kevromster commented on src/commands/git-bug-new
> +	[ "$LINE" = "" ] && rm -f "$FILE" && exit 0
аналогично с `&& exit 0`

2016-11-14 17:03 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
1) Ну собсна он выдаст алярму что такой файл уже открыт и редактируется, это же например произойдёт если сумасшедший юзер попробует одновременно создать два коммита, не совсем понимаю для чего такие зверства, но если скажете что это необходимо сделаю.
2) Чтоб уж точно не пересечься с файлами сумасшедшего пользователя дающего файлам имена начинающееся с точки.

2016-11-15 12:01 UTC, kevromster requested changes

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +		echo "Error: There's nothing here"
пользователь ничего не поймёт, увидев такое сообщение - нужно написать, чего именно не нашлось

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
Продолжу дискуссию по этой строчке - `$$` спасёт отца русской демократии от  совпадения с файлами пользователя, и внутри $GIT_DIR держать этот файл нет смысла.

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +	#Не совсем уверен как проверять невозможность поднятся выше, поэтому такой вот костыль
вообще, первая же гугл-ссылка даёт ответ :)
`git rev-parse --show-toplevel`

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +	local LINE="$(echo $(sed -n 1p $FILE | awk '$1 != "" {print $0}'))"
а что этот код делает? первую непустую строчку из файла получает?

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
в кавычки `$SUMMARY` и `$DESCRIPTION` (`$STATUS` заодно тоже можно)?

2016-11-15 12:01 UTC, kevromster commented on src/commands/git-bug-new
> +	if git show-ref --quiet --verify $REF
почему бы комментарий на добавить о том, что именно этот `if` здесь проверяет?

2016-11-15 14:54 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
Если мы полагаем пользователя настолько сумасбродным кто запрещает ему добавить в конце имени файла случайный набор цифр? Баба яга против!

2016-11-16 05:16 UTC, kevromster commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
никто же не мешает проверить, что такого файла нет у пользователя, а если есть - добавить единичку, например

2016-11-16 14:50 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	local FILE="$GIT_DIR/ISSUE_EDIT"
А, собственно, зачем делать лишнюю проверку если можно просто положить туда куда ему лезть не стоит?
Мне кажется так лучше.

2016-11-16 14:50 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
nope

2016-11-16 14:50 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	#Не совсем уверен как проверять невозможность поднятся выше, поэтому такой вот костыль
Полезный совет, спасибо.

2016-11-17 01:50 UTC, kevromster commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
хочу развёрнутый ответ почему нет

2016-11-17 09:11 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
Хм, вроде бы я уже писал, ну да ладно:
В этих переменных хранятся хэши соответствующих блобов, так как шестнадцатеричное число не содержит в своей записи пробелы это не нужно.

2016-11-17 13:18 UTC, kevromster commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
Рекомендую пересмотреть лекцию о качестве кода. Конкретно здесь проблема - плохие названия переменных - в `$SUMMARY` хранится не саммари, а хэш, и т.д.

2016-11-17 13:34 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	git update-index --add --cacheinfo 100644 $SUMMARY summary
Чтож. Изменю названия этих переменных, и подработаю прочее, что касается читаемости и самодокументированности, но в данном конкретном случае претензии мне всё же кажутся надуманными. Это как с названиями файлов никто не даёт файлу имя "Имя файла хранящего такое-то содержимое", все просто называют его "Такое-то содержимое"; хэш для гита выступает в качестве имени файла, поэтому такой вариант мне казался очевидным.

2016-11-19 06:39 UTC, kevromster commented on src/commands/git-bug-new
> +	if [ "$GIT_DIR" = "" ]
Он пустой никогда не будет сейчас. Лучше проверить на -d

2016-11-22 04:31 UTC, kevromster requested changes

2016-11-22 04:31 UTC, kevromster commented on src/commands/git-bug-new
> +	if [ -d "$GIT_DIR" ]
Инвертировать условие нужно.

2016-11-22 04:31 UTC, kevromster commented on src/commands/git-bug-new
> +		exit 1
тихий выход для пользователя - непонятно, нужно написать что-нибудь. В других местах тоже стоит добавить текстовое сообщение.

2016-11-22 04:31 UTC, kevromster commented on src/commands/git-bug-new
> +		"${EDITOR:-vi}" $FILE
У меня при тестировании vi не смог создать/сохранить файл ISSUE_EDIT.
Скрипт вообще тестировался на работоспособность? )

2016-11-22 13:54 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +		exit 1
В этом случае будет выведено стандартное сообщение гита об отсутствии репозитория, вызванное 8 строкой.

2016-11-22 13:55 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +	if [ -d "$GIT_DIR" ]
Это одна из ошибок, извините.)

2016-11-22 13:55 UTC, Tatiotaeryy commented on src/commands/git-bug-new
> +		"${EDITOR:-vi}" $FILE
Нет, мы случайно залили неисправленную версию с ошибками, сейчас всё исправим)

2016-11-23 09:36 UTC, kevromster approved these changes
LGTM

2016-11-24 12:38 UTC, merged