git-bug-resolve
edu-xored/tracker pull request #6
Opened 2016-11-09 16:59 UTC by Tatiotaeryy

2016-11-09 17:00 UTC, Tatiotaeryy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать команду закрытия тикета ('git bug resolve')](https://trello.com/c/S1c0yq9F/3-git-bug-resolve)

2016-11-10 14:55 UTC, kevromster requested changes

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +[ "$#" -eq 0 ] && exit 0
тут перед выходом хорошо бы как раз usage вывести как пользоваться скриптом. И выйти с кодом возврата на 0, а, например, 1

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +[ "$HASH" = "" ] && exit 0
предлагаю написать на экран что-то в духе "no issue found" перед выходом, и выйти можно с кодом возврата не 0, а, например, 1

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +HASH="${HASH:12:40}"
вошебный хардкод чисел тут и ниже со $STATUS. Предлагаю вынести эту магию в отдельную функцию с говорящим названием, которая выдаёт нужную подстроку из входного параметра.

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +STATUS=`echo resolved | git hash-object -w --stdin`
в двойных кавычках?

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +HASH=`git ls-tree $REF $1`
давай $1 в отдельную переменную вынесем с говорящим названием

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +git rm "$1" >/dev/null 2>&1
$1 точно должен быть в отдельной переменной

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +rm -f "./.git/index"
а зачем тут этот файл удалять?

2016-11-10 14:55 UTC, kevromster commented on src/commands/git-bug-resolve
> +[ -f "./.git/index" ] && mv -f "./.git/index" "./.git/index$$"
кстати говоря, тут везде предполагается, что я этот скрипт из корня репозитория запускаю. А если я зайду в поддиректорию? все остальные git-команды будут работать, а вот эти штуки с относительным путём "./" уже нет

2016-11-22 14:38 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +[ "$#" -eq 0 ] && exit 0
Сделанно.

2016-11-22 14:38 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +HASH=`git ls-tree $REF $1`
Хороший вариант.

2016-11-22 14:39 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +[ "$HASH" = "" ] && exit 0
Done.

2016-11-22 14:39 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +HASH="${HASH:12:40}"
Теперь его нет

2016-11-22 14:39 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +[ -f "./.git/index" ] && mv -f "./.git/index" "./.git/index$$"
Исправленно

2016-11-22 14:57 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +STATUS=`echo resolved | git hash-object -w --stdin`
Исправленно

2016-11-22 14:58 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +git rm "$1" >/dev/null 2>&1
Хорошо

2016-11-22 14:58 UTC, Tatiotaeryy commented on src/commands/git-bug-resolve
> +rm -f "./.git/index"
За тем же зачем и в git bug new

2016-11-24 13:09 UTC, kevromster approved these changes
LGTM

2016-11-25 15:05 UTC, Dimonchik0036 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать поддержку сокращенных хешей для git bug resolve](https://trello.com/c/NoWwXrwh/15-git-bug-resolve)

2016-11-29 05:14 UTC, merged