Feature/4
edu-xored/tracker pull request #7
Opened 2016-11-13 16:51 UTC by banyrule

Возникло пару вопросов при реализации:

1. Мы выводим тот же хэш, который подали на вход git bug, или хэш дерева?
2. Нужно ли выводить поле status?

2016-11-13 17:09 UTC, teabagk7 commented on src/commands/git-bug-hash
> +	# echo "Status: $STATUS"
Status нужен, это же такой же атрибут описанный в README

2016-11-13 18:25 UTC, banyrule commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать команду просмотра тикета ('git bug <hash>')](https://trello.com/c/4i1kE5FY/4-git-bug-hash)

2016-11-14 14:52 UTC, kevromster requested changes

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	touch temp$$
1) А зачем touch? Файл должен создаться, когда начнём в него писать через `>`
2) Предлагаю имя `temp$$` вынести в отдельную глобальную константу, а не повторять по всему скрипту.

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	TREE_HASH=$(echo "$2")
если передаёшь наверх значение через глобальную переменную, то лучше тогда её объявить в начале скрипта.

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +
Странное форматирование - двойной отступ. Может, все три команды рядом положить? Вполне будет гармонично смотреться.

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	git cat-file -p $TREE_HASH 1> temp$$
а зачем тут явно stdout поток как `1` указывать? просто `>` вполне бы хватило

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +
снова двойной отступ

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	echo "bug $HASH"
может, _issue_, а не _bug_?

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	HASH="$1"
что будет, если входного параметра не передано? Не вижу ни одной проверки.

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	SUMMARY=$( git cat-file -p $SUMMARY_HASH 0>&1)
И для статуса, и для summary тот же функционал уже реализован в git-bug (но по-другому).
Во-первых, где более правильная реализация? Во-вторых, предлагаю не копипастить, а создать отдельный общий скрипт с названием вроде `git-bug-common.sh` (@AnnaKhismatullina подскажет, возможно, более правильное название) и в нём определить общие функции вроде _get_status()_ и _get_summary()_.
Включать этот скрипт себе через `source` или через `.` и дёргать эти общие функи из всех мест.

2016-11-14 14:52 UTC, kevromster commented on src/commands/git-bug-hash
> +	DESCRIPTION=$(git cat-file -p $DESCRIPTION_HASH 0>&1)
А что здесь `0` означает?

2016-11-15 02:26 UTC, teabagk7 commented on src/commands/git-bug-hash
> +	touch temp$$
У меня предложение дописать скрипт git bug.
Ведь по смыслу это относится к нему.
Еще возникает вопрос зачем нам выводить хэш задачи, если он уже ввёл этот хэш? Может отказаться на выводе от него?
Скрипт не выдаст актуальную версию, т.к хэш - идентификатор _issue_, по которому мы должны выдавать актуальную версию. Сейчас выдается самая первая версия issue как понимаю.

2016-11-15 13:09 UTC, Dimonchik0036 commented on src/commands/git-bug-hash
> +	# echo "Status: $STATUS"
Done

2016-11-15 13:20 UTC, Dimonchik0036 commented on src/commands/git-bug-hash
> +
Done

2016-11-15 13:20 UTC, dimonchik0036 commented on src/commands/git-bug-hash
> +	git cat-file -p $TREE_HASH 1> temp$$
Done

2016-11-15 13:20 UTC, Dimonchik0036 commented on src/commands/git-bug-hash
> +
Done

2016-11-16 05:18 UTC, kevromster commented on src/commands/git-bug-hash
> +	touch temp$$
поддерживаю идею дописать _git-bug_ вместо отдельного скрипта.

2016-11-17 11:23 UTC, Dimonchik0036 commented
Постарался учесть все предыдущие замечания. Правильно ли я объявил `TREE_HASH` в начале?

2016-11-20 13:03 UTC, mr1name requested changes
Что за ошибка "This hash ($2) is not found."? Сообщение, что этот скрипт не нашел какой-то хэш может означать в глазах пользователя что угодно. Непонятно является ли это какой-то внутренней ошибкой, или означает ли это, что ты просто ввел что-то не то. Человек, который это увидит, скорее всего пойдет искать в интернет, что это означает, хотя скрипт должен был сообщить одну простую вещь - issue с таким идентификатором не существует. А то, что нет какого-то хэша (от которых мы возможно даже откажемся и будем как идентификатор использовать что-то другое) только запутает человека и отнимет у него лишнее время.

2016-11-20 13:11 UTC, mr1name requested changes
И еще по сообщениям, что такое "Please enter the correct data."? Откуда я знаю что является корректным? Если пользователь неправильно ввел команду, то ему сразу и надо показать, как её использовать правильно, так, чтобы он понял, что он сделал не так. Ваши сообщения об ошибках по информативности равносильны завершению программы с кодом -1, поэтому прошу присмотреться к ним повнимательнее.

2016-11-20 14:08 UTC, mr1name submitted a review, later dismissed
Информативность работы самой команды тоже близка к нулю. Как мне узнать кто создал Issue и когда, как понять, когда изменялся его статус и кто его изменял, как менялось его описание и остальные атрибуты? Плюс одного линейного пути тут недостаточно. Есть многие вещи, которые хочется видеть не всегда, например, полный список всех изменений статуса Issue с датами и именами, то есть нужны еще дополнительные параметры, которые позволяли бы видеть доп. информацию. Это самая центральная команда в проекте, потому, что если у пользователя просто не будет возможность получить большую часть какой-то полезной информации (которая у нас есть!), то никого смысла в самом проекте и нет. Для той информации которую вы сейчас выдаете пользователю, нам достаточно было бы просто хранить текстовый файл с issue и изменять его когда надо, потому что ни а какой истории изменений, и вообще всех возможностей, которые мы получили благодаря гиту, тут речи даже не идет.

2016-11-23 05:25 UTC, akhismat commented on src/git-bug
> +    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
Посколько не все команды будут содержаться в этом файле, а только git bug и git bug hash, то эта проверка нам понадобится, так что я ее восстановила из мастера.

2016-11-23 05:50 UTC, AnnaKhismatullina commented on src/git-bug
> +        *)
Из-за этого условия, все команды git bug * будут обрабатываться git_bug_hash, что не верно.
Например, попытка сделать git bug new:
```
bash -x src/git-bug new                                                                                                                                                                                                                                         (demo|…)
+ main new
+ REF=refs/heads/ISSUES
+ '[' 1 -lt 1 ']'
+ local subcommand=new
+ shift
+ case "$subcommand" in
**+ git_bug_hash new**
```

usage: git bug [-h | -a | --open | --resolved | <subcommand>]
    <subcommand> can be :
    new             create new issue
    resolve         resolve issue
    hash            prints issue information

2016-11-23 09:39 UTC, akhismat requested changes

2016-11-23 09:39 UTC, akhismat commented on src/git-bug
> +        *)
Чтобы это исправить нужно запились более аккуратный regexp, чем просто *.

2016-11-23 09:39 UTC, AnnaKhismatullina commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
Не обязательно выносить проверку в отдельный if, лучше было заменить regex в case вместо _*_ на _[a-f0-9]*_
типа:
```
        [a-f0-9]*)
            git_bug_hash "$subcommand"
            exit 0
            ;;
```

2016-11-23 09:53 UTC, banyrule commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
Возможно bug hash будет логичнее вызывать там же, где и другие команды, а в case оставить обработку флагов.

2016-11-23 09:59 UTC, kevromster requested changes

2016-11-23 09:59 UTC, kevromster commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
Я бы оставил в отдельном `if`. Но:
1) тут забыто A-F
2) текущий regex, кажется, пройдёт любое слово на _a_. А если у нас такая команда появится в будущем?

2016-11-23 10:14 UTC, AnnaKhismatullina commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
1. Честно не помню, в hash'е git'a заглявные буквы
2. Попробовала 
```
git bug add
git bug abcd
```
regex не сработал)

2016-11-23 10:22 UTC, kevromster commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
шестнадцатеричные циферки я могу и заглавными захотеть написать (или какой-нибудь инструмент мне их так отдаст).
Кстати, add - это валидное начало хэша.

2016-11-23 12:28 UTC, dimonchik0036 commented on src/git-bug
> +        *)
Done

2016-11-23 17:13 UTC, Dimonchik0036 commented on src/git-bug
> +    if expr "$subcommand" : "[a-f0-9]*" 1>/dev/null
Done

2016-11-24 08:56 UTC, Tatiotaeryy requested changes

2016-11-24 08:56 UTC, Tatiotaeryy commented on src/git-bug
> +    local status_hash="$(git cat-file -p "$(git cat-file -p $issue | awk ' /tree/ {print $2}')" | awk ' /status/ {print $3}')"
Не бейте меня палками, но в этом коде встречаются два различных подхода которые могу заставить пользователя попотеть:
1. В качестве <hash> команда "git bug <hash>" принимает хэш актуального коммита issue (последнего).
2. В качестве <hash> команда "git bug" возвращает хэш корневого коммита issue (первого), которое если верить модели выступает в качестве "имени" issue.

Это не помешает работе скрипта, но вызовет негодование пользователя, который попробовав посмотреть issue по хэшу выведенному git bug увидит, что issue не найдено, но при этом сможет его редактировать)

2016-11-24 12:10 UTC, Dimonchik0036 commented on src/git-bug
> +    local status_hash="$(git cat-file -p "$(git cat-file -p $issue | awk ' /tree/ {print $2}')" | awk ' /status/ {print $3}')"
Не совсем понятен комментарий. При поиске хэша, выведенного через `git bug`, корректно отображается полная информация по нему.

2016-11-24 12:40 UTC, Tatiotaeryy commented on src/git-bug
> +    local status_hash="$(git cat-file -p "$(git cat-file -p $issue | awk ' /tree/ {print $2}')" | awk ' /status/ {print $3}')"
Это правда, не совсем понятно написал)
Поиск по хэшу выведенному через git bug будет выдавать всегда одну и ту же информацию.

2016-11-26 04:36 UTC, kevromster approved these changes
LGTM

2016-11-26 09:55 UTC, Tatiotaeryy approved these changes

2016-11-29 05:11 UTC, akhismat approved these changes

2016-11-29 05:14 UTC, merged